const helperVar = {
  SELECTOR: "SELECTOR",
  CHRISTMAS_SPECIALS: "CHRISTMAS_SPECIALS",
  SERIES_FINALE: "SERIES_FINALE",
  FAVOURITES: "FAVOURITES",
  UPPERS: "UPPERS",
  DOWNERS: "DOWNERS"
};


export { helperVar };
